# Generated by Django 4.0.4 on 2022-05-13 11:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_sessionyearmodel_remove_students_session_end_year_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
