# Generated by Django 4.0.4 on 2022-05-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_onlineclassroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineClassRoom',
        ),
    ]
